Chris3606/GoRogue

GoRogue/EffectTrigger.cs
=> Removed indicesForRemove

GoRogue/LambdaTranslationMap.cs, GoRogue/TranslationMap.cs
This is literally the first thing I did when trying to set up map generation.  Then I figured it might be generally useful to users of the library, so I worked it into the GoRogue code to send as a PR.
=> Adding a couple helper classes to make it easier to use complex data with GoRogue algorithms

GoRogue/MapGeneration/Generators/MazeGenerator.cs, GoRogue/MapGeneration/Generators/RoomsGenerator.cs
Fix `roomMaxSize` being passed for min. 
Fixes #79 
Fixes #81 
I figured i would fix this other issue (that I filed) because I was in there fixing the room gen. 😄
=> Fix room gen code

GoRogue.Debugger/GoRogue.Debugger.csproj, GoRogue.Debugger/IRoutine.cs, GoRogue.Debugger/Interpreter.cs, GoRogue.Debugger/RoutineViewport.cs, GoRogue.Debugger/Routines/RegionRoutine.cs, GoRogue.Debugger/Routines/RotateRegion.cs, GoRogue.Debugger/Routines/SpirographRoutine.cs, GoRogue.Debugger/Routines/Spirographs.cs, GoRogue.Debugger/Spirograph.cs, GoRogue.Debugger/TileState.cs
Added some generalizations to the debugger to use in new routines
=> Debugger routine generalization

GoRogue.UnitTests/GameFramework/GameFrameworkTests.cs, GoRogue/FOV.cs, GoRogue/GameFramework/Components/ComponentBase.cs, GoRogue/GameFramework/Components/IGameObjectComponent.cs, GoRogue/GameFramework/GameObject.cs, GoRogue/GameFramework/IGameObject.cs, GoRogue/GameFramework/IGameObjectExtensions.cs, GoRogue/GameFramework/Map.cs
- Refactored GameObject to move most of the responsibility for collision detection checking, etc to Map
- Makes IGameObject easier to implement
- Refactored FOV to have Recalculated event
- Refactored Map to use Recalculated event instead of CalculateFOV functions
=> GameFramework and FOV Refactor

GoRogue.Debugger/GoRogue.Debugger.csproj, GoRogue.PerformanceTests/FOVAlgorithms.cs, GoRogue.PerformanceTests/GoRogue.PerformanceTests.csproj, GoRogue.PerformanceTests/Regions.cs, GoRogue.UnitTests/FOVTests.cs, GoRogue.UnitTests/GoRogue.UnitTests.csproj, GoRogue.UnitTests/Serialization/Comparisons.cs, GoRogue/FOV/FOVBase.cs, GoRogue/FOV/IFOV.cs, GoRogue/FOV/RecursiveShadowcastingFOV.cs, GoRogue/GoRogue.csproj, GoRogue/Pathing/WeightedGoalMap.cs, GoRogue/SenseMapping/SenseSource.cs, changelog.md
- See changelog.md diff for change summary
- Added basic tests for Region creation
=> Updated FOV API

GoRogue.UnitTests/MapGeneration/RegionTests.cs, GoRogue/MapGeneration/Region.cs
- Fixed bug where inner points are incorrectly determined
- Fixed  transformation functions to ensure the new region has corners correctly mapped
- Removed unnecessary parts of public API
- Added safety check to region constructor to prevent creating a region with invalid corners
=> Region Bugfixes

GoRogue.Debugger/Routines/GearsRoutine.cs, GoRogue.UnitTests/MapGeneration/PolygonAreaTests.cs, GoRogue/MapGeneration/IReadOnlyMultiArea.cs, GoRogue/MapGeneration/MultiArea.cs, GoRogue/MapGeneration/PolygonArea.cs
to support use cases where we want to get the sub-areas of a multi area and only want to expose the interface.
I also added a "GearsInMotion" routine that could probably be better thought out
=> Added IReadOnlyMultiArea 

GoRogue.Debugger/Routines/GearsRoutine.cs, GoRogue/MapGeneration/IReadOnlyMultiArea.cs, GoRogue/MapGeneration/MultiArea.cs
- Cleaned up documentation and squashed analyzer complaints.
=> Minor Documentation Cleanup

GoRogue.UnitTests/MapGeneration/PolygonAreaTests.cs, GoRogue.UnitTests/MapGeneration/RegionTests.cs, GoRogue/MapGeneration/PolygonArea.cs, GoRogue/MapGeneration/Region.cs
Added AreaChanged events and handler, removed pseudo-implementation of some PolygonArea methods on Region.
=> Slight Region fix

GoRogue.UnitTests/GameFramework/GameFrameworkTests.cs, GoRogue/GameFramework/GameObject.cs, GoRogue/GameFramework/IGameObject.cs, GoRogue/GameFramework/IGameObjectExtensions.cs, GoRogue/GameFramework/Map.cs, GoRogue/GoRogue.csproj, changelog.md
- HOTFIX: See changelog.md for details
=> Fixed Bug with GameFramework.Map and setting Walkability

GoRogue.PerformanceTests/GameFramework/OpenMapTests.cs, GoRogue.PerformanceTests/Pathing/AStar.cs, GoRogue.PerformanceTests/Pathing/FleeMapOpenMap.cs, GoRogue.PerformanceTests/Pathing/GoalMapOpenMap.cs, GoRogue.UnitTests/ManualTestHelpers.cs, GoRogue.UnitTests/Pathing/FleeMapTests.cs, GoRogue.UnitTests/Pathing/GoalMapTests.cs, GoRogue.UnitTests/SpatialMaps/LayeredSpatialMapTests.cs, GoRogue/GameFramework/Map.cs, GoRogue/GoRogue.csproj, GoRogue/Pathing/AStar.cs, GoRogue/Pathing/FleeMap.cs, GoRogue/Pathing/GoalMap.cs, GoRogue/SpatialMaps/LayeredSpatialMap.cs, GoRogue/SpatialMaps/MultiSpatialMap.cs, GoRogue/SpatialMaps/SpatialMap.cs, changelog.md
- Fixed bug in `FleeMap` that caused crash when its goal map used  base map with non-obstacle edges (fixed #211)
- Added unit test to check for this issue as well
- Optimized `AStar` and `FastAStar` performance (~20% speed improvement on a path across a completely open map)
- Optimized `GoalMap` performance (~50% speed improvement for a full Update on a completely open map)
- Optimized `FleeMap` performance (~40% speed improvement for a full Update on a completely open map)
- Added the capability to specify a custom `Point` hashing algorithm in spatial map implementations
- Specified a more optimal hashing algorithm in the `Map` constructor for use with the map's spatial maps.
=> Pathing Fixes and Performance Optimizations

GoRogue.UnitTests/Serialization/Comparisons.cs, GoRogue.UnitTests/Serialization/TestData.cs, GoRogue/GameFramework/Map.cs, GoRogue/GoRogue.csproj, GoRogue/IDGenerator.cs, changelog.md
=> Alpha 12 Changes

.github/workflows/dotnet-core.yml, GoRogue.Debugger/GoRogue.Debugger.csproj, GoRogue.UnitTests/Serialization/TestData.cs, GoRogue/SpatialMaps/IReadOnlyLayeredSpatialMap.cs, README.md
- Fixes minor issues created in the removal of develop-3.0.
=> Miscellaneous Develop-3.0 Fixes

GoRogue.UnitTests/DisjointSetTests.cs, GoRogue/DisjointSet.cs, changelog.md
- Fixed #266 
- Added ability to supply custom hashing algorithms to use for the items in a `DisjointSet<T>`
- Added unit tests for disjoint set structures
=> Disjoint Set Fix

GoRogue.PerformanceTests/FOVAlgorithms.cs, GoRogue.UnitTests/FOV/FOVSenseMapEquivalenceTests.cs, GoRogue.UnitTests/FOV/FOVTests.cs, GoRogue.UnitTests/FOV/RecursiveShadowcastingEquivalenceTests.cs, GoRogue.UnitTests/GameFramework/GameFrameworkTests.cs, GoRogue.UnitTests/ManualTestHelpers.cs, GoRogue/FOV/BooleanBasedFOVBase.cs, GoRogue/FOV/DoubleBasedFOVBase.cs, GoRogue/FOV/IFOV.cs, GoRogue/FOV/RecursiveShadowcastingBooleanBasedFOV.cs, GoRogue/FOV/RecursiveShadowcastingDoubleBasedFOV.cs, GoRogue/FOV/RecursiveShadowcastingFOV.cs, GoRogue/GameFramework/Map.cs, GoRogue/GoRogue.csproj, changelog.md
=> FOV and Map Fixed/Enhancements

GoRogue/Random/GeneratorExtensions.cs, changelog.md
- Added RNG extension functions for getting random positions from rectangles which correspond to the functions for other types.
=> Random Rectangle Positions

GoRogue.UnitTests/Messaging/MessageBusTests.cs, GoRogue/Messaging/ISubscriber.cs, GoRogue/Messaging/MessageBus.cs, changelog.md
=> MessageBus RegisterAll/UnregisterAll Functions

GoRogue.UnitTests/Random/GeneratorExtensionsTests.cs
- Added unit tests for Rectangle's RandomPosition function to ensure that the precisely entire extent of the Rectangle is possible to generate
=> Added Rectangle RandomPosition Tests

GoRogue.PerformanceTests/GameFramework/MapTests.cs, GoRogue.UnitTests/Pathing/AStarTests.cs, GoRogue.UnitTests/Serialization/Comparisons.cs, GoRogue/FOV/FOVCalculateParameters.cs, GoRogue/GameFramework/Map.cs, GoRogue/GoRogue.csproj, GoRogue/GridViews/InheritedTypeGridView.cs, GoRogue/SenseMapping/SenseMap.cs, GoRogue/SenseMapping/Sources/ISenseSource.cs, changelog.md
- Updated to new version of the primitives library, which contains faster `Distance` calculations
- Avoided the use of `LambdaGridView` in performance-critical views in a `GameFramework.Map`, to maximize performance.
=> Map Performance Enhancements

GoRogue.PerformanceTests/MapAreaFinders/FindMapAreasOpenMapTests.cs, GoRogue.PerformanceTests/MultiAreas/MultiAreaEnumeration.cs, GoRogue.PerformanceTests/Pathing/FleeMapOpenMap.cs, GoRogue.PerformanceTests/Pathing/GoalMapOpenMap.cs, GoRogue.PerformanceTests/SenseMapping/SenseMapAlgorithms.cs, GoRogue.UnitTests/FOV/FOVTests.cs, GoRogue.UnitTests/MapGeneration/PolygonAreaTests.cs, GoRogue.UnitTests/Pathing/FleeMapTests.cs, GoRogue.UnitTests/Pathing/GoalMapTests.cs, GoRogue.UnitTests/SenseMapping/SenseMapTests.cs, GoRogue/GoRogue.csproj, GoRogue/MapGeneration/MultiArea.cs, GoRogue/MapGeneration/PolygonArea.cs, GoRogue/MapGeneration/Steps/Translation/RectanglesToAreas.cs, changelog.md
- Updated primitives library to v1.4.1
- Edited all usage of primitives library defined functions to conform to the new API
- Added to the `IReadOnlyArea` implementations to ensure maximum efficiency while iterating.
- Updated version to an actual beta (finally!)
=> Update Primitives Library

GoRogue/GameFramework/Map.cs
=> Fixed LayersBlockingWalkability bug

.gitignore, GoRogue.Debugger/GoRogue.Debugger.csproj, GoRogue.PerformanceTests/GoRogue.PerformanceTests.csproj, GoRogue.UnitTests/GameFramework/GameFrameworkTests.cs, GoRogue.UnitTests/GoRogue.UnitTests.csproj, GoRogue/GameFramework/Map.cs, GoRogue/GoRogue.csproj, changelog.md
=> Cached Map Views in GameFramework.Map

.gitignore, GoRogue.Debugger/GoRogue.Debugger.csproj, GoRogue.PerformanceTests/GoRogue.PerformanceTests.csproj, GoRogue.UnitTests/GameFramework/GameFrameworkTests.cs, GoRogue.UnitTests/GoRogue.UnitTests.csproj, GoRogue/GameFramework/Map.cs, GoRogue/GoRogue.csproj, changelog.md
- See changelog
- Added more Map unit tests
=> 3.0.0-beta04

GoRogue/Components/ComponentCollection.cs, GoRogue/GoRogue.csproj, changelog.md
- Fixed minor warnings
- Added annotations such as "readonly" where applicable
- Updated csproj and changelog for beta5 release.
=> Update Project for Beta5 Release

GoRogue.PerformanceTests/Components/ComponentCollection.cs, GoRogue.PerformanceTests/GameFramework/MapTests.cs, GoRogue.PerformanceTests/ListCastEnumerators.cs, GoRogue.PerformanceTests/Program.cs, GoRogue.UnitTests/Components/ComponentCollectionTests.cs, GoRogue.UnitTests/GameFramework/GameFrameworkTests.cs, GoRogue.UnitTests/Mocks/MockGameObjects.cs, GoRogue/Components/ComponentCollection.cs, GoRogue/Components/IComponentCollection.cs, GoRogue/GameFramework/Map.cs, GoRogue/GameFramework/MapIterators.cs, GoRogue/GoRogue.csproj, GoRogue/ListCastEnumerators.cs, changelog.md
=> GoRogue Beta05

GoRogue/Components/ParentAware/IParentAwareComponent.cs, GoRogue/Components/ParentAware/ParentAwareComponentBase.cs, GoRogue/GoRogue.csproj, changelog.md
=> Relaxed IParentAwareComponent Type Restrictions

GoRogue/Components/ParentAware/IParentAwareComponent.cs, GoRogue/Components/ParentAware/ParentAwareComponentBase.cs, GoRogue/GoRogue.csproj, changelog.md
=> GoRogue 3.0.0-beta06

GoRogue.UnitTests/Mocks/MockFactoryItems.cs, GoRogue.UnitTests/Serialization/Comparisons.cs, GoRogue.UnitTests/Serialization/TestData.cs, GoRogue/Factories/AdvancedFactory.cs, GoRogue/Factories/Factory.cs, GoRogue/Factories/IAdvancedFactoryBlueprint.cs, GoRogue/Factories/IFactoryBlueprint.cs, GoRogue/Factories/IFactoryObject.cs, GoRogue/Factories/ItemNotDefinedException.cs, GoRogue/Factories/LambdaAdvancedFactoryBlueprint.cs, GoRogue/Factories/LambdaFactoryBlueprint.cs, GoRogue/GoRogue.csproj, GoRogue/SerializedTypes/Factories/AdvancedFactory.cs, GoRogue/SerializedTypes/Factories/Factory.cs, changelog.md
- Allowed factories to use any (hashable) type as the ID
- Implemented lambda factory blueprints for ease of use.
=> Improved Factory Implementation

GoRogue.Docs/articles/howtos/effects-system.md, GoRogue.Docs/articles/toc.yml, GoRogue.PerformanceTests/Effects/AdvancedCountingEffect.cs, GoRogue.PerformanceTests/Effects/CountingEffect.cs, GoRogue.PerformanceTests/Effects/EffectTests.cs, GoRogue.PerformanceTests/Effects/EffectTriggerTests.cs, GoRogue.Snippets/HowTos/EffectsSystem.cs, GoRogue.Snippets/Program.cs, GoRogue.UnitTests/EffectTests.cs, GoRogue.UnitTests/Effects/AdvancedEffectTests.cs, GoRogue.UnitTests/Effects/EffectTests.cs, GoRogue.UnitTests/Mocks/MockEffects.cs, GoRogue/Effect.cs, GoRogue/EffectTrigger.cs, GoRogue/Effects/AdvancedEffect.cs, GoRogue/Effects/AdvancedEffectTrigger.cs, GoRogue/Effects/Effect.cs, GoRogue/Effects/EffectBase.cs, GoRogue/Effects/EffectDuration.cs, GoRogue/Effects/EffectTrigger.cs, GoRogue/Effects/EffectTriggerBase.cs, changelog.md
- See changelog
- Added documentation article on effects system
- Added performance tests for effects system
=> Refactor Effects System

GoRogue.Docs/articles/howtos/comingsoon/fov.md, GoRogue.Docs/articles/howtos/comingsoon/spatial-maps.md, GoRogue.Docs/articles/howtos/fov.md, GoRogue.Docs/articles/toc.yml, GoRogue.Snippets/HowTos/FOV.cs, GoRogue.Snippets/Program.cs
- Added how-to article for GoRogue's FOV system.
=> Add FOV Documentation

GoRogue.UnitTests/DiceNotation/DiceNotationTests.cs, GoRogue/DiceNotation/Parser.cs
=> Fix Dice Notation Unary - Operator

changelog.md
Somehow it got removed, probably my fault...
=> Readd changelog
